from enum import Enum


class ErrorCode(str, Enum):
    # Generic
    UNKNOWN_ERROR = "UNKNOWN_ERROR"

    # Ingestion
    INGEST_FILE_NOT_FOUND = "INGEST_FILE_NOT_FOUND"
    INGEST_UNSUPPORTED_TYPE = "INGEST_UNSUPPORTED_TYPE"
    INGEST_PARSE_FAILED = "INGEST_PARSE_FAILED"
    INGEST_CHUNK_FAILED = "INGEST_CHUNK_FAILED"
    INGEST_EMBED_FAILED = "INGEST_EMBED_FAILED"
    INGEST_ALREADY_EXISTS = "INGEST_ALREADY_EXISTS"

    # Retrieval
    RETRIEVAL_QUERY_FAILED = "RETRIEVAL_QUERY_FAILED"
    RETRIEVAL_RERANK_FAILED = "RETRIEVAL_RERANK_FAILED"
    RETRIEVAL_LLM_FAILED = "RETRIEVAL_LLM_FAILED"
    RETRIEVAL_EMPTY_RESULT = "RETRIEVAL_EMPTY_RESULT"
    RETRIEVAL_TIMEOUT = "RETRIEVAL_TIMEOUT"

    # Persistence
    PERSIST_WRITE_FAILED = "PERSIST_WRITE_FAILED"
    PERSIST_READ_FAILED = "PERSIST_READ_FAILED"
    PERSIST_NOT_FOUND = "PERSIST_NOT_FOUND"
    PERSIST_CONFLICT = "PERSIST_CONFLICT"
    PERSIST_CONNECTION_LOST = "PERSIST_CONNECTION_LOST"

    # API
    API_VALIDATION_ERROR = "API_VALIDATION_ERROR"
    API_UNAUTHORIZED = "API_UNAUTHORIZED"
    API_FORBIDDEN = "API_FORBIDDEN"
    API_NOT_FOUND = "API_NOT_FOUND"
    API_RATE_LIMITED = "API_RATE_LIMITED"
    API_BAD_REQUEST = "API_BAD_REQUEST"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    HEALTH_CHECK_FAILED = "HEALTH_CHECK_FAILED"
    RESPONSE_BUILD_FAILED = "RESPONSE_BUILD_FAILED"